### ISSUE TITLE
Are you open to pull-requests?

### ISSUE THREAD

**Issue by skx** [z80playground/cpm-fat#37]
I've just submitted an order for the hardware and now I'm looking over the code.

Off the top of my head there are a couple of simple changes/contributions I'd suggest making:

* Add a `Makefile` to allow rebuilding the binaries more easily.
* Overhauling [message.asm](https://github.com/z80playground/cpm-fat/blob/main/message.asm)
* Remove the `*.symbols` files from the repository.

Are you open to pull-requests?  Or do you even have ideas of things that you'd like to see but don't have time.

(On the topic of messages I wrote some code to print "inline" strings here - [string-output.z80](https://github.com/skx/z80-examples/blob/master/string-output.z80), that could could almost be dropped inline, I'd just wrap the entry with `push af`, and `exx` to preserve the registers.   Without the hardware I can't test, but I _think_ that should preserve everything neatly and avoid the stack-juggling you've come up with :)

**Comment by z80playground** [comment]
Thanks Steve. I've been really busy recently and I am only just starting to get back on top of this project. I totally agree about the symbol files. I never use them. A Makefile is a good idea. I use VSCODE and have it all on a hot-key, but I see what you mean. Yes, message.asm is a bit of a mess!
