### ISSUE TITLE
Enable Gorilla Game

### ISSUE THREAD

**Issue by gd-99** [z80playground/cpm-fat#41]
Hi, recalling the GORILLA.BAS game released for QBasic I found a compiled GORILLA.COM version here: [https://github.com/sblendorio/gorilla-cpm](https://github.com/sblendorio/gorilla-cpm) found under binary. Initially this wouldn't work using CP/M-FAT. The game will load but then bail out after selecting (3) ANSI terminal with a "Bad BDOS call 0069". 

Looking up this BDOS call I found a reference here: [http://members.iinet.net.au/~daveb/cpm/bdos.html](http://members.iinet.net.au/~daveb/cpm/bdos.html) where a reference to call 69 indicates BDOS function 69 - Get configuration table address. Supported by: CP/Net. Can't think why this would be compiled into the game? Could it be played over a network???

**The solution:** I have found using my implementation (no reason it shouldn't work on the Z80 Playground) of CP/M-FAT is to include the following code snip-it into DBOS.ASM around line 55 after the cp $66 block:

`cp  $69                            ;BDOS function 69 - Get configuration table address `
` jr  z, return_255_in_a      ;Supported by: CP/Net.`   

Recompile DBOS and copy over the bdos.bin file to the memory stick and Gorilla is good to go. Nice looking graphical game.

Enjoy...

Edited to reformat the code layout - the jr comes on the line after cp.

**Comment by gd-99** [comment]
I missed you can have attachments so here are a couple of screen shots of Gorilla.com running on my z80...
![Gorilla1](https://user-images.githubusercontent.com/33517190/111964857-fad35180-8aec-11eb-89a9-d2d15583366d.png)
![Gorilla3](https://user-images.githubusercontent.com/33517190/111964885-0161c900-8aed-11eb-8d40-271546c12200.png)

**Comment by z80playground** [comment]
Yes, I'll do this fix in the next release.

**Comment by z80playground** [comment]
It's fixed in release 1.09
